file = open("C:/Users/Caabars/Desktop/deneme2.txt","w")
file.write("Selam")
file.close()
file = open("C:/Users/Caabars/Desktop/deneme2.txt", "w", encoding="utf-8")
file = open("C:/Users/Caabars/Desktop/deneme2.txt", "a", encoding="utf-8")
file.write("معلش\n")
file.close()
file = open("C:/Users/Caabars/Desktop/deneme2.txt", "a", encoding="utf-8")
file.write("-Haha komiksin\nمعلش")
file.close()
